### ISSUE TITLE
Make it explicit?

### ISSUE THREAD

**Issue by ajoslin** [ahdinosaur/evalify#4]
I'd like to use this module, but I really don't like the idea of my code doing things that aren't self-documented by the code itself. If one of my files is being run and stringified during the compile step, I want the file to say that in its own code.

Implicitly transforming code via config file, with the code telling you nothing, is bad practice IMO.

I'd like something like this:

myfile.js
```js
const evalify = require('evalify')
module.exports = evalify({
  foo: expensiveCalculation()
})
```

package.json
```js
{
  "browserify": {
    "transform": ["evalify/transform"]
  }
}
```

Evalify by default would just be an identity function. 

Then `evalify/transform` would instantiate a `static-module` for evalify that replaced the function call with a JSON.stringify'd version of the first argument.

We could also consider making `evalify` error in the browser if the transform hasn't been run to replace it with JSON.stringify.

This explicit way would produce much saner and understandable code. Thoughts?

If you approve, I can open a PR.

**Comment by ajoslin** [comment]
With this, you could also run `evalify` on anything, even just one line in a file.

**Comment by ahdinosaur** [comment]
hey @ajoslin, this is a really interesting idea. part of me likes the explicitness, part of me prefers how it works now.

what's most pressing for me is how this would drop support for dynamic modules:

```js
// config.js
const envToObj = require('env-to-obj')
const pick = require('object.pick')

const config = envToObj(process.env)

const browserConfig = pick(config, [
  'url',
  // ...
])

module.exports = evalify(browserConfig)
```

for this specific use case, i have already wrote my own [transform](https://github.com/ahdinosaur/conjig/blob/master/transform.js) to do [configuration](https://github.com/ahdinosaur/conjig/) separate from `evalify`, so could continue doing something like that.

as for my other use case, [`vas`](https://github.com/ahdinosaur/vas) services in [`catstack`](https://github.com/enspiral-root-systems/catstack), where i don't want the developer to think about how it's being 'eval-ified' on the client-side, but i could also just write a more targeted browserify transform for my use case, which is probably better anyways.

---

@mmckegg what do you think?

**Comment by ajoslin** [comment]
Six months later, this issue came to mind.

I recently found a different module that solves my problem: https://github.com/kentcdodds/babel-plugin-preval

Specifically when used with babel-macros (see the macros section of the above readme).
